language: ruby
gemfile:
  - test/config/gemfiles/Gemfile.rails-3.2.x
#  - test/config/gemfiles/Gemfile.rails-3.1.x
#  - test/config/gemfiles/Gemfile.rails-3.0.x
rvm:
  - 1.9.3
#  - 1.8.7
env:
  - DB=mysql
#  - DB=mysql2
#  - DB=postgresql
before_script:
  - bundle exec rake db:create DB=$DB
  - bundle exec rake db:create DB=etl_execution
  - bundle exec rake db:migrate DB=$DB
